### ISSUE TITLE
LCN / NCN rendering

### ISSUE THREAD

**Issue by scrapperuk** [gravitystorm/OpenCycleMap-Mapping-Guide#3]
Has something recently changed on the way OCM renders LCN & NCN routes from Openstreetmap tags and adds the familiar "glow"

We have seen a lot of locally mapped routes disappear , we know that they were previously tagged LCN : yes (or LCN : Potential)

The table of tags on the OpenStreetMap wiki for Opencyclemap suggests that these tags are no longer used. We've changed a lot of routes to Network :LCN to try and resurrect their rendering, and are waiting for tile updates but we know of adjoining campaign groups that have seen a similar set of evaporating routes

**Comment by gravitystorm** [comment]
Questions are better sent to info@gravitystorm.co.uk, otherwise I might not notice them on a decade-old repository!

In saying that, yes, the rendering changed a year ago to no longer support `lcn=yes` and similar tags directly on ways. Route relations have been the preferred method of tagging for a long time now, and are reasonably easy to create in most editors.
